name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: false

      - name: Verify Go environment
        run: |
          go version
          go env

      - name: Build
        run: go build ./...

      - name: Test
        run: go test -v ./...
